"""Service for generating comprehensive, human-readable incident reports."""

from __future__ import annotations

from app.models.decision_engine import DecisionEngineResponse
from app.models.report_generation import IncidentReportResponse


def _section_team(decision: DecisionEngineResponse) -> list[str]:
    rec = decision.team_allocation
    if rec.status == "success" and rec.selected_team:
        t = rec.selected_team
        specs = ", ".join(t.specialties) if t.specialties else "None"
        status = "COMMITTED to this incident" if decision.dispatch_committed else "proposed (not committed)"
        return [
            f"**{t.team_name}** (Specialty: {specs}) - {status}",
            f"- Distance from incident: {t.route_distance_km} km",
            f"- Estimated arrival: {t.estimated_travel_time_minutes} mins",
            f"- Reasoning: {t.rationale}",
        ]
    lines = ["No team can be dispatched by road."]
    if rec.fallback:
        lines.append(f"- Fallback: {rec.fallback.advice}")
    else:
        lines.append(f"- {rec.explanation}")
    return lines


def _section_facility(rec, selected, name: str, noun: str, unit: str) -> list[str]:
    if rec.status == "success" and selected:
        return [
            f"**{name}**",
            f"- Distance: {selected.route_distance_km} km",
            f"- Estimated travel: {selected.estimated_travel_time_minutes} mins",
            f"- Capacity: {selected.available_capacity} {unit} available",
            f"- Reasoning: {selected.rationale}",
        ]
    lines = [f"No {noun} reachable by a safe road."]
    if rec.fallback:
        lines.append(f"- Fallback: {rec.fallback.advice}")
    return lines


def generate_incident_report(decision: DecisionEngineResponse) -> IncidentReportResponse:
    """Generate a deterministic incident report from a server-issued decision bundle."""

    prediction = decision.prediction
    sim = decision.simulation
    blocked = ", ".join(r.road_id for r in sim.blocked_roads) or "None"
    basis = (
        "scenario preset inputs (not live sensor data)"
        if decision.input_basis == "scenario_preset"
        else "caller-supplied rainfall inputs"
    )

    lines: list[str] = [
        "# RescueTwin AI Incident Report",
        "",
        f"**Incident Zone:** {decision.incident_zone_id}",
        f"**Priority:** {decision.priority.upper()}",
        f"**Scenario:** {sim.scenario.value.upper()}",
        "",
        "## Situation Summary",
        f"Using {basis}, the baseline model predicts flood severity **{prediction.predicted_flood_severity}/100** "
        f"({prediction.confidence.upper()} confidence"
        + (f", typical error ±{prediction.expected_error_points} points" if prediction.expected_error_points is not None else "")
        + f"). The district-wide scenario simulation scores **{sim.severity_score}/100**.",
        f"- **Affected zones:** {len(sim.affected_zones)}",
        f"- **Blocked roads:** {len(sim.blocked_roads)} ({blocked})",
        f"- **Incident zone isolated by flooded roads:** {'YES' if decision.incident_isolated else 'No'}",
        "",
    ]

    if decision.warnings:
        lines += ["## Warnings", *[f"- {w}" for w in decision.warnings], ""]

    if decision.damage_assessment:
        dmg = decision.damage_assessment
        lines += [
            f"## Image Assessment (from {dmg.filename})",
            f"- **Indicative level:** {dmg.damage_level.value.upper()}",
            f"- **Estimated water-coloured coverage:** {dmg.water_coverage_pct}%",
            f"- **Method:** {dmg.method} (no statistical confidence available)",
            f"- **Rationale:** {dmg.rationale}",
            f"- *{dmg.disclaimer}*",
            "",
        ]

    hosp = decision.hospital_recommendation
    shelt = decision.shelter_recommendation
    lines += ["## Operational Recommendations", "", "### 1. Recommended Hospital"]
    lines += _section_facility(
        hosp, hosp.selected_hospital, hosp.selected_hospital.hospital_name if hosp.selected_hospital else "", "hospital", "beds"
    )
    lines += ["", "### 2. Recommended Shelter"]
    lines += _section_facility(
        shelt, shelt.selected_shelter, shelt.selected_shelter.shelter_name if shelt.selected_shelter else "", "shelter", "spots"
    )
    lines += ["", "### 3. Rescue Team Assignment", *_section_team(decision)]
    lines += ["", "---", "*Generated by RescueTwin AI. Decision-support prototype built on a fictional district and synthetic data; not for real emergency use.*"]

    return IncidentReportResponse(report_content="\n".join(lines))
